apiVersion: v2
name: parallax-app
description: Helm chart for deploying Parallax internship frontend and backend microservices with Istio Service Mesh support
type: application
version: 0.2.0
appVersion: "1.16.0"
