apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/global: "true"
plugin: prometheus
config: {}