{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parallax-app.backend.fullname" . }}
  labels:
    {{- include "parallax-app.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http-backend
      protocol: TCP
      name: http
  selector:
    {{- include "parallax-app.backend.selectorLabels" . | nindent 4 }}
{{- end }}
