{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parallax-app.frontend.fullname" . }}
  labels:
    {{- include "parallax-app.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http-web
      protocol: TCP
      name: http
  selector:
    {{- include "parallax-app.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
