{{- if .Values.ingress.enabled }}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
plugin: rate-limiting
config:
  minute: 5
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
plugin: key-auth
config:
  key_names:
    - apikey
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: my-consumer
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
username: api-user
credentials:
  - my-api-key
---
apiVersion: v1
kind: Secret
metadata:
  name: my-api-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  kongCredType: key-auth
  key: secret123
{{- end }}
