apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: parallax 

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: salehktk005/simple-node-app:v1

        imagePullPolicy: IfNotPresent

        ports:

        - containerPort: 5000

        env:
        - name: PORT
          value: "5000"
        - name: SERVICE_NAME
          value: "backend"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

        resources:

          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 5
          periodSeconds: 5